Разметка главной страницы
htmlacademy-htmlcss/1542427-sedona-30 pull request #2
Opened 2021-01-26 14:50 UTC by TatsianaGr

2021-01-27 07:56 UTC, maxzbest requested changes

2021-01-27 07:56 UTC, maxzbest commented on index.html
> +				<img src="https://via.placeholder.com/800x256" alt="Фото города">
В макете это изображение контентное или декоративное?

2021-01-27 07:56 UTC, maxzbest commented on index.html
> +				<img src="https://via.placeholder.com/800x256" alt="Фото природы">
В макете это изображение контентное или декоративное?

2021-01-27 07:56 UTC, maxzbest commented on index.html
> +			<div>
Формы пока не размечаем

2021-01-27 07:56 UTC, maxzbest commented on index.2.html
> +<!DOCTYPE html>
Файл должен называться catalog.html

2021-01-27 07:56 UTC, maxzbest commented on index.2.html
> +     <p>Сортировка</p>
"По цене", "По типу", "По рейтингу" забыла

2021-01-27 07:56 UTC, maxzbest commented on index.2.html
> +      <p>Подробнее</p>
Лишний тег

2021-01-27 07:56 UTC, maxzbest commented on index.2.html
> +   <article>
Сможешь объяснить в нашем чатике причину использования article здесь?

2021-01-28 11:56 UTC, TatsianaGr commented
По поводу изображений. Как я понимаю, эти являются контентными. Мне так их оставить? 27.01.2021, 10:56, "Maksim" <notifications@github.com>:
@maxzbest requested changes on this pull request.



In index.html:
> +			</ul>
+		</nav>
+	</header>
+	<main>
+		<img src="https://via.placeholder.com/456,65x350,88" alt="Welcome Sedona">
+		<img src="https://via.placeholder.com/1200x272" alt="Фон для текста">
+		<h1>СЕДОНА-НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ,ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h1>
+		<p>РАССМОТРИМ 5 ПРИЧИН</p>
+		<section>
+			<div>
+				<h2>Настоящий городок</h2>
+				<p>— №1 —</p>
+				<p>Седона - не аттракцион для туристов, там течёт своя жизнь</p>
+			</div>
+			<div>
+				<img src="https://via.placeholder.com/800x256" alt="Фото города">

В макете это изображение контентное или декоративное?



In index.html:
> +					<p>Всегда заказывайте фирменный бургер, вы не разочаруетесь!</p>
+				</li>
+				<li>
+					<h2>Сувениры</h2>
+					<p>Не только китайского, но и местного производства!</p>
+				</li>
+			</ul>
+		</section>
+		<section>
+			<div>
+				<h2>Там есть Мост дьявола</h2>
+				<p>— №2 —</p>
+				<p>Да, по нему можно пройти! Если конечно вы осмелитесь</p>
+			</div>
+			<div>
+				<img src="https://via.placeholder.com/800x256" alt="Фото природы">

В макете это изображение контентное или декоративное?



In index.html:
> +				<li>
+					<h2>красивая дорога</h2>
+					<p>— №4 —</p>
+					<p>ехать в седону из лас-вегаса совсем не скучно!</p>
+				</li>
+				<li>
+					<h2>мало туристов</h2>
+					<p>— №5 —</p>
+					<p>большинство едет в гранд каньон и толпится там</p>
+				</li>
+			</ul>
+		</section>
+		<section>
+			<p>Заинтересовались?</p>
+			<p>Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в седоне</p>
+			<div>

Формы пока не размечаем



In index.2.html:
> @@ -0,0 +1,104 @@
+<!DOCTYPE html>

Файл должен называться catalog.html



In index.2.html:
> +   		<li>Парковка</li>
+   		<li>wi-fi</li>
+   	</ul>
+   	<p>Тип жилья</p>
+   	<ul>
+   		<li>Гостиницца</li>
+   		<li>Мотель</li>
+   		<li>Апартаменты</li>
+   	</ul>
+   	<p>Стоимость в сутки</p>
+   	<p>Показать</p>
+   -->
+   <article>
+    <div>
+     <p>Найдено:3</p>
+     <p>Сортировка</p>

"По цене", "По типу", "По рейтингу" забыла



In index.2.html:
> +   	<p>Показать</p>
+   -->
+   <article>
+    <div>
+     <p>Найдено:3</p>
+     <p>Сортировка</p>
+     <img src="https://via.placeholder.com/11x10" alt="стрелка">
+     <img src="https://via.placeholder.com/11x10" alt="стрелка">
+   </div>
+   <ul>
+     <li>
+      <img src="https://via.placeholder.com/135x90" alt="фото гостиницы">
+      <p>Amara Resort & Spa></p>
+      <p>Гостиница</p>
+      <p>От 4000 Р.</p>
+      <p>Подробнее</p>

Лишний тег



In index.2.html:
> +  	<p>Инфаструктура:</p>
+   	<ul>
+   		<li>Бассейн</li>
+   		<li>Парковка</li>
+   		<li>wi-fi</li>
+   	</ul>
+   	<p>Тип жилья</p>
+   	<ul>
+   		<li>Гостиницца</li>
+   		<li>Мотель</li>
+   		<li>Апартаменты</li>
+   	</ul>
+   	<p>Стоимость в сутки</p>
+   	<p>Показать</p>
+   -->
+   <article>

Сможешь объяснить в нашем чатике причину использования article здесь?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-02 08:00 UTC, merged